#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# superuser not required for some system commands
for x in mount umount sv pacman updatedb su ; do
	alias $x="doas -- $x"
done

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \

# Colorize commands when possible.
alias \
	ls="ls -lahN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="doas -- shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="paru" \
	xi="doas -- xbps-install" \
	xr="doas -- xbps-remove -R" \
	xq="xbps-query" \
	z="zathura" \
	s="doas --" \
	wg="wordgrinder" \
	rc="reflex-curses" \
	rpg="~/.local/bin/rpg-cli" \
  wacom="sh ~/.config/wacom/config.sh"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="curl wttr.in | less" \
	pu="paru -Syyu --ignore neovim --ignore xkeyboard-config --noconfirm" \
